### ISSUE TITLE
Adding Content on the Front Page

### ISSUE THREAD

**Issue by aniketmaithani** [asetalias/asetalias.github.io#1]
# To DO's
- [x] About ALiAS 
- [x] Upcoming Workshop/Meetup
- [x] Contact Info [mailing list, fb group, other form of contact]
- [x] LOGO for the website

**Comment by aniketmaithani** [comment]
#WIP :)

**Comment by thisisayush** [comment]
Logo Done

**Comment by aniketmaithani** [comment]
@thisisayush can you also handle the content part a bit ??? 

@bhanuvrat your take over this??? What should we write in ABOUT ALiAS section?

**Comment by aniketmaithani** [comment]
cc @arcolife @mysticTot

**Comment by thisisayush** [comment]
@aniketmaithani U mean updating the about ALiAS Section?

**Comment by aniketmaithani** [comment]
@thisisayush the entire content... as in validation and keep it updated as the development goes on.

**Comment by thisisayush** [comment]
@aniketmaithani Yeah, I'm on it. I will be sending patches occasionally as and whenever required :)

**Comment by Tanya-Jain** [comment]
#20 Updated the About section partially. Still need information about alumni and how the club came to be. Also, updated the data of events previously organised.

**Comment by aniketmaithani** [comment]
I am closing this as of now. In case anyone wants to open this up, feel free to do so.
