### ISSUE TITLE
[Update] Event Details 

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#100]
Need a **maintainer** to update the event.json file on a short notice and submit PR's 
- When new events are added.
- Old events need to be removed.
- Edit and promote current and upcoming events.

@thisisayush Add Help Needed tag and yayy 100th issue

**Comment by thisisayush** [comment]
For information on updating events refer to: https://github.com/asetalias/asetalias.github.io/wiki/Site-Management:-Events

**Comment by thisisayush** [comment]
Thanks @utkarsh2102.
