### ISSUE TITLE
[Change] Fork me on Github 

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#101]
- Found a cool new "Fork me on Github" icon that is implemented both on the new Pyladies website and Pydelhi Website. It looks better and can be customized according to our website.

- Add the icon and define a correct position for it.

**Comment by Manas-kashyap** [comment]
I would like to take this task

**Comment by omi10859** [comment]
so, how you are planning to do the task @Manas-kashyap

**Comment by vipulgupta2048** [comment]
Thanks @Manas-kashyap for showing your interest in the same. Please go ahead. Make sure to go through the Readme.md before proposing a PR.

**Comment by thisisayush** [comment]
@vipulgupta2048  We still doing this?
Also, @Manas-kashyap Any update if we're still doing this?

**Comment by vipulgupta2048** [comment]
Technically speaking, I actually deleted the button from the Footer. So this issue doesn't exist. 
Closing, as the Fork me on GitHub, is kinda pointless.
