### ISSUE TITLE
Links are not clickable in communities section  

### ISSUE THREAD

**Issue by omi10859** [asetalias/asetalias.github.io#107]
Links are not working in the description, for communities here http://asetalias.in/communities.html 
Json file http://asetalias.in/data/communities.json also need to be fixed for using a href form links instead of this  **Website:**[http://ilugd.github.io](\"http://ilugd.github.io\")"

**Comment by omi10859** [comment]
We need to fix it asap as we are using JSON for our app also

**Comment by thisisayush** [comment]
Thanks for reporting it @omi10859 . Will fix it ASAP.

**Comment by omi10859** [comment]
If no one is taking up this task, please assign to me lets see what I can do. @thisisayush 
Also, @Tanya-Jain what about the new version is it ready?
- Are you using StaicJinja?
- Are you using same JSON files? As they are used in our app if not you need to inform us.

**Comment by thisisayush** [comment]
@omi10859 Please post the changes you're going to do before taking up the issue. Keep in mind the text is stored in Markdown Format in JSON Files and is parsed and converted to HTML during the build.

**Comment by omi10859** [comment]
I was thinking to use simple [bootstrap cards](https://getbootstrap.com/docs/4.0/components/card/) and simple text in JSON.
@utkarsh2102 would you like to take up this task?

**Comment by thisisayush** [comment]
@sagarkansal are you working on the issue?

**Comment by sagarkansal** [comment]
Yes i am working on that . Will commit ASAP

**Comment by iryanjan18** [comment]
Not yet fixed?

**Comment by thisisayush** [comment]
Fixed in bb3af45475649f17ce9ccc0247f8dc6029d52a38
Closing now.
