### ISSUE TITLE
White Space Issue in Mobile

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#11]
There is some white space coming in the right side on Mobile i.e. Small Screens.
Unable to detect the cause. Need Help!
See Screenshot for more info

**Comment by thisisayush** [comment]
![screenshot 22](https://cloud.githubusercontent.com/assets/22245433/21748480/2624920e-d5ac-11e6-80a2-793f8d5567ee.png)

**Comment by aniketmaithani** [comment]
@thisisayush any updates on this?? I am unable to see this issue on my screen. 

if this issue still persist please send a PR and reference it here. In case it is completed, you can close this issue. :)

**Comment by aniketmaithani** [comment]
@thisisayush your take on this?? should I close this ??

**Comment by thisisayush** [comment]
@aniketmaithani This issue is still present! Will work on it soon.

**Comment by thisisayush** [comment]
Fixed in PR #21

**Comment by aniketmaithani** [comment]
resolved. closing this.
