### ISSUE TITLE
[enhancement] member blogs

### ISSUE THREAD

**Issue by atb00ker** [asetalias/asetalias.github.io#123]
As per the disscussion with @anuvrat on Oct, 8'2018 during community call.
A member activity blog would be a great idea, take inspiration from pydelhi blogs: https://pydelhi.org/blog/?ref=home

All the members from second and third year are requested to write multiple 300-400 word tweet-like small blogs to help encourage newcomers. Example (from my personal experience, yours might be completely different):
- Why did i switch to linux
- Why do i work in open-source
- Talks that i have given & why do i encourage everyone to give talks
etc..etc..

I would be posting my examples blogs here soon!
I refined version of such blogs from all the members is greatly appreciated.

Thank You.

**Comment by akshat0047** [comment]
Community Unpacked
==================

The first time, getting introduced to the world of development, it left me amazed! I explored a number of technologies in the initial days of my B.Tech just for the sake of knowledge and after working on few of them at last chose, web development as my primary field.
One of my classmate suggested me to join ALiAS, a coding community of Amity University, Noida which was the main branch of our college.

 > The biggest motivation lies within YOU

Starting with small projects like webpages, learning HTML + CSS + JS like every front-end developer out there, cheers !

I came across situations where I celebrated the success of my code and on the other hand irritated, when it did not worked, even after multiple attempts of mine. I asked my doubts in the community whatsapp group, became part of great discussions, listened to experiences etc. It was going perfect but….

Soon, I realized that there were not much people involved into such productive things in my surrounding.
Few of them were busy in mugging up the notes and most of them in typical college activities. I came across my friends who had the will to learn, few of them even working in some fields but not progressing much.
What we lacked was **Guidance, Healthy Discussions, Doubts, Ideas, Collaboration, Team Work and much more** but there was no appropriate solution to this in our college or surroundings.

It was time and we need to set up a community in our surrounding as well but we had no idea who will lead the same.

> Not every time we’re in the lack of ideas but, we’re in the lack of courage to bring them alive !!

I was looking for some guidance until I came across one of my senior from the ALiAS community,   
Mr. Ayush Agarwal who encouraged me to open a sister community of ALiAS in Amity Lucknow.
This marked the start of my real journey, not as a developer or mentor but as a leader, with in my support people from various fields whether they would be my friends, head community members etc.

I showed an immense interest to transform it into a successful community which is still in the process, and the best part being, it made me learn a lot which was not limited up to technical skills instead from **management of events, to becoming a speaker, arranging webinars, promoting my juniors to indulge in the same**, overall making an experience worth sharing.

**ALIAS LUCKNOW** established in 2018 is a chapter of ALIAS (Amity Linux Assistance Sapience), Noida which is a part of well known coding societies in the NCR.

We have a mutual aim to promote the use of open source among the students and help them become great developers in the future. The main motive of the club is to encourage students to code and make contributions to the open source projects, also, we have a mutual interest in working on great projects in teams to make innovations out of ideas.

Our community is not limited to a specific field instead we believe to strive in every direction, until perfection is achieved. We usually discuss our ideas in the college time apart from this all the members are added in a whatsapp group where knowledge sharing is on _24x7 basis_.

We do organize meetups on particular topic by mutual discussion which gives everyone a chance to code and learn together about the technology within a healthy and competitive environment in the end proving to be a quality based community striving hard to reach levels  of excellence.

@atb00ker @vipulgupta2048

**Comment by vipulgupta2048** [comment]
Thanks @akshat0047, 
But time and again, I have told you to read the README of the [ALiAS blog](https://github.com/asetalias/ALiAS_Blog/blob/master/README.md) and make a *PR* there. 

Here are the instructions that you need to follow, clearly listed [here](https://github.com/asetalias/ALiAS_Blog/blob/master/README.md).

> Instruction for Writers:
> The Language used for blog posts is Markdown
> 
> Fork and clone the repository. For instructions on doing that, please refer to instructions for developers
> Create you work file in /content/post, see existing files as an example.
> To run a local copy of the website, open the command prompt or your preferred CLI, change the directory to the address of the repository and use the command hugo server if you have hugo installed. For instruction on Hugo installation and use, refer to Hugo installation and setup Section.
> Submit a pull request to submit your work.

Please make a Pull Request.

**Comment by vipulgupta2048** [comment]
Alongwith, this issue can be put to rest since we have begun initiation of https://github.com/asetalias/ALiAS_Blog

**Comment by akshat0047** [comment]
ok, will follow the same on the blog repo as soon as possible.

**Comment by thisisayush** [comment]
Shall we close the issue now, since the blog is up and running? We can add it to README on how to add your blogs to ALiAS.

**Comment by vipulgupta2048** [comment]
Yo, let me just link that, the contributor guide for the blog is on the blog.

**Comment by vipulgupta2048** [comment]
![Screenshot_2019-10-20_12-13-50](https://user-images.githubusercontent.com/22801822/67155791-20c25880-f333-11e9-8d7b-ced2963b2d12.png)
Just gonna leave it here, I don't like to commit image files, anymore.

**Comment by vipulgupta2048** [comment]
![Uploading Screenshot_2019-10-20_12-20-17.png…]()
Another one.

**Comment by vipulgupta2048** [comment]
tick
