### ISSUE TITLE
[Proposal] To keep Thursday meetups as passive event on website

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#132]
**Discussion on passive events**
- How about keeping the Thursday meetups as our passive event on the website. 
- Maybe make a poster that could be updated on the website after every event and stay there till the next event.
- Everyone one who visits the website can check it out, and then ask about the fine details on the group. 
- This would lead to making the Thursday meetings, be more structured and a definite event that happens for the community outreach?
Tagging discussion @thisisayush @parthsharma2 @omi10859 @Tanya-Jain @atb00ker and everyone else for an open discussion.

**Comment by thisisayush** [comment]
LGTM. Setting a specific time (say 2 PM) would make it more organized.

**Comment by Sc0rpi0n101** [comment]
Great idea. 
I'd also suggest a mention of the Saturday weekly calls somewhere. We also need to get the calls a little more organized.

**Comment by vipulgupta2048** [comment]
2 Flashcards then, one for an offline local event, one for online events and free to watch.

**Comment by vipulgupta2048** [comment]
Didn't we finish this as well? Closing in favor of #166
