### ISSUE TITLE
Setup automatic build of StaticJinja through tags per PR

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#137]
Many first-time contributors find it hard to set up the complete build environment, I suggest creating a mirror repository on Gitlab to automatically build the HTML when changes are pushed to the repository or a tag is created. This will encourage more first-time participation.

**Comment by thisisayush** [comment]
Let's setup travis instead. Anyone up for the job to automatically build the code when pushed?

**Comment by vipulgupta2048** [comment]
On it, if no one takes it up.

**Comment by vipulgupta2048** [comment]
On second thought, this will make contribution easier. But, only if the people are making changes in the right file. We need to do something about static and templates.

**Comment by vipulgupta2048** [comment]
Update: we are also considering GitHub Actions.
Courtesy: Ex-VIP-VP @parthsharma2 :hatching_chick:

**Comment by vipulgupta2048** [comment]
So, there is a bit of a hiccup with Travis. As you can see I have got it working. But, for Travis to move over to the deploy part we need to give an output out of the build.py script. Whereas the build.py finishes execution with this as the last line `Press Ctrl + C to stop` 

Need help regarding how to emulate the keystroke through the .travis.yml file and then deploy merged PR's on GitHub Pages.

**Comment by thisisayush** [comment]
Travis implemented for automated build and deployment. Thanks to @vipulgupta2048. Closing this now.
