### ISSUE TITLE
Parse new blog posts and display on website

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#145]
Now that the blog is installed at http://asetalias.in/blog, it would be good to display it's link somewhere like the Menu?

**Comment by thisisayush** [comment]
@vipulgupta2048 Any suggestions on 3rd Party service? The Link's been already added to menu.

**Comment by vipulgupta2048** [comment]
Noice, PyCon uses something called Whirlwind with their Pelican generated
blogs. Let's see what works best with Hugo

We can be using feed2JS or feed.js
Need to make an RSS feed for the Hugo blog though, if not already
generated. Lemme look around, assign me to this.
