### ISSUE TITLE
Facebook not showing up!

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#146]
Check this out!
Who uses Facebook anyways, let's have our own blog feed linked to this. 
![Screenshot_2019-06-07_23-45-22](https://user-images.githubusercontent.com/22801822/59125360-c2966980-897f-11e9-8223-7857239fa18a.png)

CC: @thisisayush

**Comment by thisisayush** [comment]
Seems okay here. You sure it's not a slow connection or adblocker something?

![image](https://user-images.githubusercontent.com/22245433/59144930-86541f00-89fa-11e9-8a6d-9a5f3de8f71f.png)

**Comment by thisisayush** [comment]
@vipulgupta2048 Any update on the issue?

**Comment by vipulgupta2048** [comment]
Adblocker roger that, closing.
