### ISSUE TITLE
[REDESIGN] Home Page Hero Section

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#147]
Proposed layout for hero section

Current:
![image](https://user-images.githubusercontent.com/22245433/59172910-1a8fc480-8b68-11e9-812b-ff06234e88a9.png)

Proposed (Something Like):
![image](https://user-images.githubusercontent.com/22245433/59172930-38f5c000-8b68-11e9-8ac0-5772626b853e.png)

We split this into two sections, the left and right. A little skewed. Left m we place the text in bold and CTA buttons and right m a slideshow of our events.
IMAGE HERE will be a slideshow of images.

**Comment by vipulgupta2048** [comment]
@Sc0rpi0n101 Also, please start the discussion. Someone needs to start the fire of rebuilding the website. At this point, I am just hoping to do whatever it takes.

**Comment by sksuryan** [comment]
![Design - 1](https://user-images.githubusercontent.com/42460131/70308923-52837600-1832-11ea-8b80-125299b00d63.png)
![Web 1920 – 1](https://user-images.githubusercontent.com/42460131/70308936-5b744780-1832-11ea-84eb-58af4a0719f2.png)
Designs for the Home Page Hero section. Looking forward for your feedback and suggestions.

**Comment by thisisayush** [comment]
The second One looks neat with the social bar from the first one.
Also, can we use something else instead of those tech icons in the bottom right? 
Third, what about the mobile layout? How will it look there?

**Comment by sksuryan** [comment]
Still working on the Mobile layout.
Also, what else do you want to add to the bottom right instead of the icons?

**Comment by sksuryan** [comment]
![iPhone X-XS-11 Pro – 2@2x](https://user-images.githubusercontent.com/42460131/70350692-319c3e80-188d-11ea-8f46-7e7b795fc800.png)
![iPhone X-XS-11 Pro – 1@2x](https://user-images.githubusercontent.com/42460131/70350696-3234d500-188d-11ea-8975-80de17b43ba5.png)

![iPhone X-XS-11 Pro – 5@2x](https://user-images.githubusercontent.com/42460131/70350787-77f19d80-188d-11ea-9fde-503844f5a916.png)
![iPhone X-XS-11 Pro – 1@2x](https://user-images.githubusercontent.com/42460131/70350788-77f19d80-188d-11ea-9215-59c10687f4e6.png)
![iPhone X-XS-11 Pro – 2@2x](https://user-images.githubusercontent.com/42460131/70350790-788a3400-188d-11ea-8101-f6d5835788c3.png)
![iPhone X-XS-11 Pro – 4@2x](https://user-images.githubusercontent.com/42460131/70350791-788a3400-188d-11ea-9df3-5964892251a3.png)

The Mobile layouts are attached. Looking forward for your feedbacks.

**Comment by swarnimarun** [comment]
Not sure but maybe something simpler like this would look better,
![image](https://user-images.githubusercontent.com/19930870/70374696-85edff80-191b-11ea-8a27-f1dfd5f1bff2.png)
![image](https://user-images.githubusercontent.com/19930870/70374883-b040bc80-191d-11ea-84e7-729ef70aefe4.png)
![image](https://user-images.githubusercontent.com/19930870/70374864-98693880-191d-11ea-8d9e-4bdeee1648cb.png)

**Comment by Nikhil-Soni-21** [comment]
> ![Design - 1](https://user-images.githubusercontent.com/42460131/70308923-52837600-1832-11ea-8b80-125299b00d63.png)
> ![Web 1920 – 1](https://user-images.githubusercontent.com/42460131/70308936-5b744780-1832-11ea-84eb-58af4a0719f2.png)
> Designs for the Home Page Hero section. Looking forward for your feedback and suggestions.

Second one looks great.

**Comment by thisisayush** [comment]
So we've 3 votes on the second one.

**Comment by thisisayush** [comment]
Second one looks good, but I find swarnim one a bit clean in desktop view. Maybe we can take the best of both? Simple and Clean from Swarnim's, social bar from 1st one and menu from second one?

**Comment by sksuryan** [comment]
I think, Swarnim's hamburger menu looks good for mobile..

**Comment by sksuryan** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/42460131/71586577-bd2d8600-2b40-11ea-99cf-f8b0ab9f87d4.png)
![iPhone X-XS-11 Pro – 1](https://user-images.githubusercontent.com/42460131/71586582-bf8fe000-2b40-11ea-8408-26f9e07788fc.png)

**Comment by Sc0rpi0n101** [comment]
How about we keep the buttons the same as the previous design? 

Can you change the background color of the right side from black to the current color of the hero section? How does that look?

**Comment by sksuryan** [comment]
![Web 1920 – 2](https://user-images.githubusercontent.com/42460131/71640934-9fcff780-2cb9-11ea-8ac4-40faeeec3a48.png)
upon taking the feedback into account, this is what I came up with.

**Comment by Sc0rpi0n101** [comment]
You changed too much bro.
The sidebar looks better to the right :+1: 
But the straight split through the middle looks kinda dull. 
Can you bring back the slanted split?

>  ![image](https://user-images.githubusercontent.com/30147327/71667722-497fb900-2d8c-11ea-83e6-3bc8b615bfdc.png)

Also, can you use the Join now & know more placements from this one?

**Comment by sksuryan** [comment]
> You changed too much bro.
> The sidebar looks better to the right 
> But the straight split through the middle looks kinda dull.
> Can you bring back the slanted split?
> 
> > ![image](https://user-images.githubusercontent.com/30147327/71667722-497fb900-2d8c-11ea-83e6-3bc8b615bfdc.png)
> 
> Also, can you use the Join now & know more placements from this one?

Alright bro, I'll make the changes needed..

**Comment by sksuryan** [comment]
![Web 1920 – 3](https://user-images.githubusercontent.com/42460131/71676274-d1be8800-2da5-11ea-9490-9fffb7ead69d.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/42460131/71676275-d3884b80-2da5-11ea-870c-7786c74d86e7.png)
These are the two mock ups with only difference being the placement of the call for action buttons..

**Comment by thisisayush** [comment]
I vote for the first one

![image](https://user-images.githubusercontent.com/22245433/71710657-6fa46800-2e23-11ea-9311-3dc5ee87a59d.png)

**Comment by Sc0rpi0n101** [comment]
Great
So, if no one else has any more suggestions,
Let's implement that @sksuryan

**Comment by sksuryan** [comment]
> Great
> So, if no one else has any more suggestions,
> Let's implement that @sksuryan

So, the font used is Lilita One for welcome message, and Montserrat for everything else..

**Comment by Sc0rpi0n101** [comment]
You can work on that, right?
or do you want someone else to work on it if you don't have the time?

**Comment by sksuryan** [comment]
It's actually been just over a month, since I got started with web development, so, I'll need some time, if that's not a problem..

**Comment by Sc0rpi0n101** [comment]
No, it's not a problem.
No one else is doing anything anyways. xD

**Comment by Sc0rpi0n101** [comment]
If you run into any problem, just create a WIP Pull Request and the others can help you with that.

**Comment by sksuryan** [comment]
Alright..

**Comment by Sc0rpi0n101** [comment]
Can someone assign this to @sksuryan

**Comment by Sc0rpi0n101** [comment]
Done in #209. Closing this now
