### ISSUE TITLE
[REDESIGN] Making a Popup Box for Upcoming Events

### ISSUE THREAD

**Issue by a4aditya** [asetalias/asetalias.github.io#148]
Integrating a Popup box for upcoming events at the start of the website. Any suggestions related to code or design are most welcome!!

**Comment by thisisayush** [comment]
https://github.com/asetalias/asetalias.github.io/blob/master/templates/components/_header.html#L17-L24

@a4aditya This is the part you are looking for.

And this is where you can find the js which decides if it's visible or not
https://github.com/asetalias/asetalias.github.io/blob/master/js/functions.js#L1-L18

**Comment by thisisayush** [comment]
@a4aditya any update?

**Comment by a4aditya** [comment]
I will update you in a week and hopefully a pull request in a week or so

**Comment by thisisayush** [comment]
@a4aditya You still working on this?

**Comment by Sc0rpi0n101** [comment]
Suggestion from #93 :

Create 2 boxes, one that would contain posters on the left and the other on the right with ample space for the description to be accommodated keeping all the fine details same.
