### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by hemanthtech** [asetalias/asetalias.github.io#154]
i suggest you to use https://megatags.co  for best meta tags

and use this also https://www.seoptimer.com/meta-tag-generator

**Comment by thisisayush** [comment]
That's actually a good idea for the SEO of the website.

**Comment by vipulgupta2048** [comment]
@hemanthtech Would you like to take this up?

**Comment by hemanthtech** [comment]
Yes sure

**Comment by vipulgupta2048** [comment]
Thanks for responding, go ahead open a PR for this. 
Also, we need some help regarding design as we are updating the site. If you like to contribute more, check out the issues that are open at the moment. It would be great to have folks like you contribute.
Thanks again!

**Comment by hemanthtech** [comment]
Yes can i get to know what are you ideas for the design

**Comment by vipulgupta2048** [comment]
Thanks, please checkout the issues. Specifically #147 as we are finalising the Hero Page section. You can DM me here (https://bit.ly/z2048) and we can get you added to the workgroup on Whatsapp. If you like to commit, there is good work to be done.
