### ISSUE TITLE
Changing the alumni section 

### ISSUE THREAD

**Issue by aniketmaithani** [asetalias/asetalias.github.io#16]
- [ ] Instead of Photos just a two line about the whereabout of the ALiAS alumni. 

e.g : 

" Alumni who were a part of ALiAS are now placed in various companies or some of them are still consulting other(s) in the `open source` domain.... blah blah <:P>"

**Comment by aniketmaithani** [comment]
let me know if you guys are willing to work on this issue @thisisayush @parthsharma2

**Comment by thisisayush** [comment]
@aniketmaithani I am adding a 
<div>
 Alumni who were a part of ALiAS are now placed in various companies or some of them are still consulting other(s) in the open source domain.... blah blah <:P>
</div>
and removing the photo part from the alumni box?

**Comment by thisisayush** [comment]
@aniketmaithani Proposed Changes are done. Check new Pull request #17

**Comment by aniketmaithani** [comment]
Closing this as it is done in 584eba9fcaf8a4a6b62b498e5a05ec264eb0f8c0
