### ISSUE TITLE
[ENHANCEMENT] add footer at the bottom of the index.html

### ISSUE THREAD

**Issue by SuvamPrasd** [asetalias/asetalias.github.io#172]
There should be a footer at the bottom of the index.html page. So, I am going to add the footer i.e, ©2019 ALiAS Pvt. Ltd. at the bottom of the homepage.

**Comment by vipulgupta2048** [comment]
Hello @SuvamPrasd, thanks for contributing to ALiAS. 
We already have a footer and a PR open to refactor it #165   
ALiAS is an open-source college community, not a private corporation or a company. Here's a definition of what `Pvt Ltd.` is entitled for.   

```
A private limited company, or LTD, is a type of privately held small business entity, in which owner liability is limited to their shares, the firm is limited to having 50 or fewer shareholders, and shares are prohibited from being publicly traded. A company becomes an independent legal structure when it incorporates.
```
We would love your help in solving other issues. Please [check and comment](https://github.com/asetalias/asetalias.github.io/issues) to get more information. Till then, closing this. Thank you!
