### ISSUE TITLE
Create page/section for ALiAS Swag 

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#174]
Due to a lot of requests from people to get the ALiAS swag pack, I think it would be a great idea if we could host a passive form on the website itself. That way, anyone interested can add their name to the list and get one. 

What say?

**Comment by thisisayush** [comment]
I say "Closing this" and labelling it "invalid" :P

**Comment by vipulgupta2048** [comment]
Roger that.
