### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#176]
Maybe overkill, since I am the only one opening issues and closing them. 
But, needed nonetheless.

**Comment by vipulgupta2048** [comment]
Also, @thisisayush I think we should copy the parts of the Wiki guide into a file called CONTRIBUTORS, that way GitHub auto-detects it and shows it to people on the right when they are opening new PR's or issues. It might be good that way.

**Comment by thisisayush** [comment]
Closing this.
