### ISSUE TITLE
Take up Long Dead PRs

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#186]
There a lot of PRs lying there dead since contributors are not able to give time to those issues, if you're a first-time-contributor or looking for "where to start" or just simply want to contribute to ALiAS because I know it's awesome, taking over these PRs would be good.

List of PRs that have not received any communication back from 1+ months:
- [x] #164 
- [x] #159 
- [x] #158 
- [x] #157 
- [x] #156 
- [x] #113

**Comment by vipulgupta2048** [comment]
Close them all, #180 solves them. Just checked, except if we want to add COS as mentioned in #159 
#113 has already been taken care of by #177 


![](https://cultofthepartyparrot.com/parrots/hd/sassyparrot.gif)

**Comment by thisisayush** [comment]
Converted it to list. Let's cross out what all is done.

**Comment by vipulgupta2048** [comment]
Only took a month to finish all the issues, PR's and old data problems that we were facing. 
Full steam ahead for v2 (or is it v3 now)?
