### ISSUE TITLE
Revamp the Communities Page (Discussion)

### ISSUE THREAD

**Issue by Nikhil-Soni-21** [asetalias/asetalias.github.io#190]
Need To Change the Layout of Community Page

**Comment by longevitytina** [comment]
Hi, are there any more details? I'm looking to contribute, but not sure what this is referring to.

Thanks!

**Comment by thisisayush** [comment]
Hi @longevitytina ,
Thanks for picking up this task. What we're looking for is some new design and layout for the communities page (https://asetalias.in/communities.html)

There's an ongoing discussion on Revamping the hero section of the home page, so maybe we can follow the same design pattern for the communities page too? Checkout #209 

TLDR; you're free to design the page as you see fit as long as everyone approves.

**Comment by longevitytina** [comment]
Hi @thisisayush,
I'm thinking of trying to make the page a bit more compact with each community as a small card component, here's a quick sketch:

<img width="589" alt="Screen Shot 2020-06-01 at 9 11 11 PM" src="https://user-images.githubusercontent.com/49009626/83479100-796edd80-a44c-11ea-94f4-86663724c6d9.png">

**Comment by thisisayush** [comment]
This looks ok, but can you maybe provide a little more space for description? The page aims to be a guiding and starting point to open source communities for the beginners, so we need to accomodate enough info. Also, do check the data json file for the communities to see if your design is compatible with the data or if data needs to be modified in any way.

**Comment by Sc0rpi0n101** [comment]
I think it might be better to have two tiles per line instead of three with some margin on either side and between them. That will look better and give us a lot of space for the description also. If any of the descriptions don't fit there, it's too long anyway IMO. we should shorten that.

I also think we should have a different section for conferences. I don't think PyCon India is a 'community' per se. So, it'll be better to have a different section for that. We can even add more conferences to that section.

**Comment by ritwik9857** [comment]
Hey! Is this issue still up for grab?
I want to have a go at it. Please let me know if I can take this up.

**Comment by Sc0rpi0n101** [comment]
Hi @ritwik9857 

This has already been done in #216. But if you'd still like to help, there are a lot of other pages we would appreciate your help with. 

You can check out #192 and see which page/section you can help us with.

**Comment by Sc0rpi0n101** [comment]
I'm closing this as this is done in #216
