### ISSUE TITLE
[Base Issue] Discuss Base Theme and UI

### ISSUE THREAD

**Issue by rohanvtk** [asetalias/asetalias.github.io#192]
* Hero Section [#147]
* Section
    - Journey
    - Why should I Join
* Team Section/Page [#193 ]
* Event Section/Page [#95 ]
* Webinar Section/Page [#194 ]
* Communities Page [#191 ]
* Open Source Programs [#191 ]
* UI Functionalities [#192 ]
    - Header/Menu
    - Footer
    - Colors
    - Layouts → Card, flat, etc
    - Meta Tags
* Project Section/Page [#195 ]

- [x]  Hero Section

- [ ]  Section (journey & why should I join)

- [ ]  Team Section

- [x]  Event Section

- [ ]  Webinar Section

- [x]  Communities Page

- [ ]  Open Source Programs

- [ ]  UI Functionalities

- [ ] Project Section

**Comment by thisisayush** [comment]
This issue will serve as a base issue to get into specific issues for each section and/or part of the website.

**Comment by Sc0rpi0n101** [comment]
@rohanvtk Can you also add a checklist of all the pages so that we can keep a track of the progress?

**Comment by rohanvtk** [comment]
@Sc0rpi0n101 done!

**Comment by ritwik9857** [comment]
I would like to work on #192 - UI functionalities but I am not sure what exactly is required to achieve here,
I am new to open source contribution. Would be a great help if someone can assist in the same. Thank You!

**Comment by Sc0rpi0n101** [comment]
Hi @ritwik9857, 

The whole purpose of this is to revamp our website, which you can check at https://asetalias.in/
So, you can pick any of the sections of the home page and help us redesign that. You can check #209 for reference to see the hero section redesign. 

You can check the [GitHub Workflow Guide](https://guides.github.com/introduction/flow/) for getting started.  There are also other guides at https://guides.github.com/ to help you get started. And if you still have more questions, you can ask here.

**Comment by Sc0rpi0n101** [comment]
Hi @ritwik9857, have you found something you'd like to help with?

**Comment by ritwik9857** [comment]
Hi @Sc0rpi0n101 
I am currently trying to run this project on my local machine and once it runs I will try to visit it thoroughly and then I will see the places where I can contribute.

**Comment by ritwik9857** [comment]
I am thinking to take up on #191 
Can I get more information into this issue?
As in what are the requirements or how this page should look so that I can start on that accordingly

**Comment by Sc0rpi0n101** [comment]
I've commented on the issue about all this, you can check that out.

**Comment by Sc0rpi0n101** [comment]
Hi @ritwik9857, Do you still plan on working on this issue? 
I have described what you need to do in https://github.com/asetalias/asetalias.github.io/issues/195#issuecomment-654423208

**Comment by Sc0rpi0n101** [comment]
I'm closing this as I've created a repo project for tracking the progress.
