### ISSUE TITLE
[Discussion] Webinar Page

### ISSUE THREAD

**Issue by Sc0rpi0n101** [asetalias/asetalias.github.io#194]
Create a new page for previous webinars and move the existing webinars to the new page from Home page.

Discuss the theme of the page

**Comment by ydocsgnillats** [comment]
I'd like to help with this if it is available!

**Comment by Sc0rpi0n101** [comment]
Yeah, sure. Help is always appreciated 🙂

Do you know what you need to do or should I tell you a little?

**Comment by ydocsgnillats** [comment]
I think I understand the idea behind it, but could you explain more just in case?

**Comment by Sc0rpi0n101** [comment]
So, you can check out the current webinars at https://asetalias.in/index.html#webinars. We're planning to move them to a new page, and only leave a couple of the latest webinars on the front page. 

You can take a reference to how the new theme should look like from the home page hero section and https://asetalias.in/communities.html

**Comment by ydocsgnillats** [comment]
I've created a pull request with the changes made, let me know if it's done right!
