### ISSUE TITLE
[Discussion] Revamp Projects Page

### ISSUE THREAD

**Issue by Sc0rpi0n101** [asetalias/asetalias.github.io#195]
Discussion for the new theme and design of Projects page

**Comment by Sc0rpi0n101** [comment]
This page is currently not too useful with a couple of ALiAS projects which are not even active and two other projects. 

I'm thinking we can use this page as a reference to all the projects ALiAS members have created or contributed to. The members can add their projects here. 

Whenever someone asks to suggest some open source projects to start contributing to, we can refer them to this page.

**Comment by Sc0rpi0n101** [comment]
CC: @vipulgupta2048 @thisisayush

**Comment by vipulgupta2048** [comment]
+1 on transforming this page into sourcing projects that everyone makes as a public directory. Maybe divide it as per beginner, intermediate, and advanced. To save up on effort, we can have a nice README instead on a new repo. What say?

**Comment by Sc0rpi0n101** [comment]
I'm not sure how would we divide projects into these categories. All the projects will probably have some beginner, intermediate, and advanced issues. So, I don't know how we can accurately classify the projects. 

A readme for what exactly? If you mean a readme to list the projects, what will we do with the projects page then?

**Comment by Sc0rpi0n101** [comment]
Hey @ritwik9857, 

thanks for showing interest in this issue. For reference, this is how the page looks currently. 
You are free to design the page as you wish, as long as all the members agree to that. But, looking at how the current redesign is going, you should keep the theme and color scheme somewhat similar to https://asetalias.in/communities.html. 

You can update the tile style as you seem fit to your theme, just don't lose some of the information in the current tiles, like the language tags, no of contributors, and the important links to the project. Other than that, you can have it however you want. We can discuss more in the reviews. 

We are also planning a lot more projects in the page from our members so that it can serve as a go-to for any of our community members looking for open source projects to contribute. But you don't need to worry about that. It's my job to provide you with the projects and their details. You should focus on the design.

Happy Contributing 🚀
