### ISSUE TITLE
Update the previous events page as per the current theme 

### ISSUE THREAD

**Issue by Sc0rpi0n101** [asetalias/asetalias.github.io#220]
The previous events page was designed as per the previous theme. The page also needs to be updated as per the current redesign of the website.

**Comment by priyanshu0405** [comment]
Hi @Sc0rpi0n101, I would like to take the issue.

**Comment by Sc0rpi0n101** [comment]
Sure

**Comment by priyanshu0405** [comment]
Can you please explain it to me a bit.

**Comment by Sc0rpi0n101** [comment]
Yeah, so, currently the previous events page is https://asetalias.in/prev_events.html. But it has an outdated design according to the previous design. We are redesigning the website, so we would like this page to also be designed as per the new theme. You can check the new theme from the communities page here https://asetalias.in/communities.html. 

and here is the PR for that work if you need a reference https://github.com/asetalias/asetalias.github.io/pull/216.

The instructions for building the website can be found in the wiki here https://github.com/asetalias/asetalias.github.io/wiki/Building-the-Website. 

I'm assigning the issue to you since you're interested. If you need any more help, please let me know.

**Comment by priyanshu0405** [comment]
@Sc0rpi0n101, please have a look at the PR and also suggest improvements. Thanks!!
