### ISSUE TITLE
"Shivam Rajput" picture is missing in "Meet Our Team" 

### ISSUE THREAD

**Issue by kmlhsn** [asetalias/asetalias.github.io#221]
**Describe the bug**
picture  of "Shivam Rajput" is missing in "Meet Our Team" 

**To Reproduce**
1. Go to  'https://asetalias.in/' or home page from your local machine. For example, my local URL is "http://localhost:63342/asetalias.github.io/"
2. Scroll down to 'Meet Our Team'
4. Picture of "Shivam Rajput" is missing

**Expected behavior**
There should have a picture of "Shivam Rajput"

**Screenshots**
![image](https://user-images.githubusercontent.com/32615215/89870620-f13d4f00-dbd7-11ea-90d8-487ef0bc7a5f.png)

**System Configuration**
 - What OS do you use?
Ans: Windows 10
 - Which browser do you and its version?
Ans: Mozilla Firefox version 79.0

**Comment by Sc0rpi0n101** [comment]
Fixed in #225
