### ISSUE TITLE
"Ethical Hacking & Cyber security Workshop" box is out of alignment in " PREVIOUS EVENTS "

### ISSUE THREAD

**Issue by kmlhsn** [asetalias/asetalias.github.io#222]
**Describe the bug**
"Ethical Hacking & Cyber security Workshop" box is out of alignment in " PREVIOUS EVENTS "

**To Reproduce**

1. Go to https://asetalias.in/ or or home page from your local machine. For example, my local URL is "http://localhost:63342/asetalias.github.io/".
2. Click on "PREVIOUS EVENTS" on the top menu.
3.Scroll down to "Ethical Hacking & Cyber security Workshop".

**Expected behavior**
"Ethical Hacking & Cyber security Workshop" box and date inside should be on same alignment of the other box .

**Screenshots**
![image](https://user-images.githubusercontent.com/32615215/89906131-cf11f400-dc0c-11ea-93f1-ae05b676d8f6.png)

**System Configuration**
 - What OS do you use?
Ans: Windows 10
 - Which browser do you and its version?
Ans: Mozilla Firefox 79

**Comment by AbhipsaGuru1012** [comment]
@kmlhsn Hi, can I work on this issue?

**Comment by Sc0rpi0n101** [comment]
Hi, thanks for proposing to help. 
This issue will be solved under #228. You can help with that PR with reviews and ideas. 

You can also take up other pages if you would like, like the FAQ page(#149), the team page(#193) or the supporters' page(#152)
