### ISSUE TITLE
Landing View // Hero

### ISSUE THREAD

**Issue by vinayaknayar** [asetalias/asetalias.github.io#239]
Hero is the section just below navbar (landing view). You can propose a better design for this.

![Image](https://user-images.githubusercontent.com/98237998/183346567-d07b00d3-fc7d-4189-971a-179dc63f719f.png)

![Image](https://user-images.githubusercontent.com/98237998/183351215-b922dcae-e3d3-467b-b19f-0cb9144c1cda.png)

**Comment by SagarDeep1811** [comment]
Hey ! I'd like to work on this component.
