### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Blaster4385** [asetalias/asetalias.github.io#255]
Create wireframes for the redesign of the website.

## Website Structure

The website will be divided into the following main sections:

1. **Home (`/`)**
    - [ ] #256
    - [ ] #257
    - [ ] #258
    - [ ] #259
    - [ ] #260
    - [ ] #261
2. **About Us (`/about`)**
    - [ ] #263
    - [ ] #264
    - [ ] #265
3. **Community (`/community`)**
    - [ ] #266
    - [ ] #267
    - [ ] #268
    - [ ] #269
4. **Blog (`/blog`)**
    - [ ] #270
    - [ ] #271
    - [ ] #272
5. **Projects (`/projects`)**
    - [ ] #273
    - [ ] #274
    - [ ] #275
6. **Events (`/events`)**
    - [ ] #276
    - [ ] #277
    - [ ] #278
7. **Sponsorship (`/sponsorship`)**
    - [ ] #279
    - [ ] #280
    - [ ] #281
8. **Contact Us (`/contact`)**
    - [ ] #282
    - [ ] #283

**Comment by Maniktherana** [comment]
Covered under issues with ASoC tags and new milestones
