### ISSUE TITLE
Major Structural Changes 

### ISSUE THREAD

**Issue by rplusleqaulsj** [asetalias/asetalias.github.io#3]
Following changes need to be implemented besides general HTML elements such as lists, maps and forms:

Pre-Note:
I have created a notepad file (content.txt) to the repository wherein we need to pool in text/content that will actually go under various headers in the website.

1.On top below nav-bar the default Jumbotron needs to be added with bullet scrolling See Here (Flipboard)] this will require considerable JQuery integration based on DOM tree in HTML

2.There needs to be a Learn More button on defult jumbotron right at the middle as shown here

3.There needs to be a scroll to top button See here Note: Ignore if nav-bar always on top

4.Latest News needs to go either along sidebar as in Here or in the upcoming events part but then we need some system to not clog the area with content.

5.Add Our Team Tab before Contact Tab

6.Social Media Links need to go in the Contacts tab See Here

7.Finally add Join Us in contact Tab

Will update soon on more changes

**Comment by thisisayush** [comment]
I have introduced data.js instead of content.txt!

**Comment by aniketmaithani** [comment]
@rplusleqaulsj can you have a look at your proposed changes and adjust this issue accordingly.

**Comment by thisisayush** [comment]
@rplusleqaulsj Following are fixed:
1. content.txt is replaced by data.js
2. Not Required as Intro Section of website is displaying all data :)
3. Menu is sticky. So, not required.
4. Events Section Added to accomplish the task.
5. Our Team Section Added in Pull Request #17 
6. Social Links added by @parthsharma2 
7. Join Us Button Added in Pull Request #17 

If satisfied, this issue can be closed :)

**Comment by rplusleqaulsj** [comment]
Seems nice to me. Alright close it.

**Comment by aniketmaithani** [comment]
closing this up.

**Comment by rplusleqaulsj** [comment]
nice work guys the website is looking decent. The syntax is done, content
and semantics should be finished by this week
