### ISSUE TITLE
Events Gallery : Fix About section for "Job Readiness"

### ISSUE THREAD

**Issue by diyabhandari** [asetalias/asetalias.github.io#302]
![Screenshot 2024-01-28 095937](https://github.com/asetalias/asetalias.github.io/assets/140702816/25e41652-0d03-4af2-aaf4-58f2bce281fa)
The about section of the Job Readiness event is the same as for Hacktoberfest.

**Comment by X3nyy** [comment]
i am taking this 👍

**Comment by Vyogami** [comment]
Fixed
