### ISSUE TITLE
Improve Color Scheme!!

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#44]
Suggesting themes module instead of random color!

**Comment by ATB00ker** [comment]
Tanya is working on that.

**Comment by AnimeshVerma17** [comment]
I can help in that too.

**Comment by aniketmaithani** [comment]
Guys @thisisayush @ATB00ker @AnimeshVerma17 make sure you post the same color scheme over here.

**Comment by AnimeshVerma17** [comment]
Sure we will.

**Comment by AnimeshVerma17** [comment]
Would it be better to create a complete UI style guide for the site... to maintain design consistency in further updates?

**Comment by thisisayush** [comment]
@aniketmaithani @AnimeshVerma17 @ATB00ker 
Instead of building guidelines ourself we can go Material UI?

**Comment by ATB00ker** [comment]
Completely onboard with that idea!

**Comment by aniketmaithani** [comment]
Couple of things : 
1. Let's have a design guide
2. Let's have a common FONT, COLOR w.r.t to the website theme. I have seen in the past that people tend to use different font schemes in every PR they submit. It would be great if we put this in the design specs as well.

**Comment by AnimeshVerma17** [comment]
Yes, a complete design guide specifies common fonts too.
My opinion is to trash the calligraphic fonts.......keep the typography bold but simple :) .

**Comment by thisisayush** [comment]
I suggest dividing things. Creating of a new file style.css that will include only Font and Background Styles of each element of the website while layout.css to position and define other properties of elements of page.

**Comment by AnimeshVerma17** [comment]
@thisisayush That all will be divided on the basis of design guide............it won`t be good to link too much CSS files.

**Comment by thisisayush** [comment]
All suggestions and views are welcome :)

**Comment by thisisayush** [comment]
Design has been updated in #55 . Closing this issue
