### ISSUE TITLE
Nav_bar not working in multitasking mode in Windows 

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#51]
![capture](https://cloud.githubusercontent.com/assets/22801822/24384544/37926c96-1382-11e7-9e47-2bfcd4ad015b.PNG)

The button on the top isn't working when windows are tabbed in multitasking mode in windows 10. The button is unresponsive and the hyperlinks are behaving abnormally.Please do check the photo attached  with the issue.

**Comment by thisisayush** [comment]
It seems to be working fine on my side! Please recheck!

![screenshot 52](https://cloud.githubusercontent.com/assets/22245433/24388077/0d174f40-1396-11e7-933a-0da26aeeee37.png)

**Comment by AnimeshVerma17** [comment]
Yeah it`s working all good on my browser too..... I don`t think there`s any issue here.

**Comment by thisisayush** [comment]
@vipulgupta2048 After being verified from two people here. I am closing the issue now.

**Comment by vipulgupta2048** [comment]
@thisisayush I want to add to this issue that the problem specifically arrives when the windows are divided 50-50 in the multitasking mode. It doesn't work on my system, please do check while doing the above example... I may be wrong or there is an issue with my laptop. I will recheck on some other laptop. You need to stack the windows side by side . 

![capture](https://cloud.githubusercontent.com/assets/22801822/24412213/7444452e-13f5-11e7-8712-fc6481c2bfd2.PNG)

**Comment by AnimeshVerma17** [comment]
@vipulgupta2048 checked on side-by-side stacking too. No glitches found.
![capture](https://cloud.githubusercontent.com/assets/24977899/24419561/29eb4bd6-140d-11e7-9b93-6ae90424285a.PNG)

**Comment by vipulgupta2048** [comment]
I accept the issue. Thank you for taking the time for this issue.
