### ISSUE TITLE
Adding section for showcasing projects done under ALiAS or members of ALiAS 

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#74]
I am thinking if we should add a page for showcasing projects done or ongoing under ALiAS or members of ALiAS or if someone wants to list their project for help.
Require views. @Tanya-Jain @ATB00ker @vipulgupta2048 @parthsharma2

**Comment by parthsharma2** [comment]
Nice idea. I think it'll be pretty cool.

**Comment by vipulgupta2048** [comment]
The North agrees.

**Comment by AnimeshVerma17** [comment]
Yea that's great.
And I need public opinion on using CSS grid and card layouts.
