### ISSUE TITLE
Add Alumni Section

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#83]
Add Alumni Section to Website, to let members know that previous members are in a great position today.

Suggested by @atb00ker @Manas-kashyap @thisisayush

**Comment by atb00ker** [comment]
I did not suggest anything, kindly remove my username. :)

**Comment by atb00ker** [comment]
I did not suggest anything and i am not aware of this, maybe it is a wrong tag.
Please remove my handle.
Thank you.

**Comment by vipulgupta2048** [comment]
This has been completed, isn't it?

**Comment by vipulgupta2048** [comment]
AGAIN, this has been completed. Closing...
