### ISSUE TITLE
Re-design Back-To-Top Button

### ISSUE THREAD

**Issue by thisisayush** [asetalias/asetalias.github.io#89]
The Back to Top Button in Lower Right of Website doesn't match the site theme and needs to redesigned.

**Comment by JoyBhalla** [comment]
Can i work on this ?

**Comment by thisisayush** [comment]
Sure. Let me assign it to you.

**Comment by thisisayush** [comment]
Do keep posting updates :)

**Comment by thisisayush** [comment]
Fixed in #102
