### ISSUE TITLE
frontend changes : 

### ISSUE THREAD

**Issue by aniketmaithani** [asetalias/asetalias.github.io#9]
- [x]  Need to align the `alumni` in the header
![screen shot 2017-01-08 at 2 26 27 am](https://cloud.githubusercontent.com/assets/920701/21745116/119ff736-d54a-11e6-9e83-0d489a479a9a.png)

- [x]  Alignment of the `TEST EVENT` to be adjusted. 
![screen shot 2017-01-08 at 2 26 32 am](https://cloud.githubusercontent.com/assets/920701/21745123/1fa464e8-d54a-11e6-96b8-76c00fd29af4.png)

- [x] Make Contact Us Part height bit small : should be like a small strip ideally. 
![screen shot 2017-01-08 at 2 26 39 am](https://cloud.githubusercontent.com/assets/920701/21745128/338be12a-d54a-11e6-8e95-aa0a61b00782.png)

**Comment by aniketmaithani** [comment]
@thisisayush can you work on this???

**Comment by aniketmaithani** [comment]
WIP #14

**Comment by thisisayush** [comment]
@aniketmaithani I'm on it!

**Comment by aniketmaithani** [comment]
@thisisayush already completed by commit 446e83767e3ac17842f0557988bf656f552690d5

**Comment by aniketmaithani** [comment]
closing this as of now.
