### ISSUE TITLE
New design proposal for Upcoming Events Section

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#93]
Right now, posters are not able to fit properly in the upcoming events section, also the design is somewhat small hence various elements flow out of their boxes which leads to problems and looks bad. 

**Solution**
Create 2 boxes, one that would contain posters on the left and the other on the right with ample space for the description to be accommodated keeping all the fine details same.

**Comment by thisisayush** [comment]
Can you upload a rough sketch or wireframe of proposed design?

**Comment by akshat0047** [comment]
Taking this issue

**Comment by Sc0rpi0n101** [comment]
Closing in favor of #148
