### ISSUE TITLE
Update Contact Us

### ISSUE THREAD

**Issue by vipulgupta2048** [asetalias/asetalias.github.io#97]
Add the following to the Contact Us section
- Telegram Invite links to ALiAS groups
- MM ??
- GitLab/AsetAlias
- Twitter
- Instagram 
- Integrate paper.dropbox.com links of **[ALiAS]Resources** and **Welcome to ALiAS** docs and other documents wherever required on the website. 
- Others

**Comment by JoyBhalla** [comment]
I can do this,and i've recently seen various contact us animations that look very slick,can i try it here ?

**Comment by vipulgupta2048** [comment]
Go for it. Keep us posted.

**Comment by JoyBhalla** [comment]
Can someone else take this  ? Busy with internship and other OSS projects.

**Comment by thisisayush** [comment]
Closing this now. Thanks to @vipulgupta2048 for their contribution.
